#!/bin/sh

BEARSSL_PUSHER_SOURCES='
src/codec/ccopy.c
src/codec/dec16be.c
src/codec/dec32be.c
src/codec/enc16be.c
src/codec/enc32be.c
src/codec/enc32le.c
src/codec/enc64be.c
src/hash/ghash_ctmul.c
src/hash/multihash.c
src/hash/sha1.c
src/hash/sha2small.c
src/int/i31_add.c
src/int/i31_bitlen.c
src/int/i31_decmod.c
src/int/i31_decode.c
src/int/i31_encode.c
src/int/i31_fmont.c
src/int/i31_modpow2.c
src/int/i31_montmul.c
src/int/i31_muladd.c
src/int/i31_ninv31.c
src/int/i31_sub.c
src/int/i31_tmont.c
src/int/i32_div32.c
src/mac/hmac.c
src/mac/hmac_ct.c
src/rand/hmac_drbg.c
src/rand/sysrng.c
src/rsa/rsa_i31_pub.c
src/ssl/prf.c
src/ssl/prf_sha256.c
src/ssl/ssl_client.c
src/ssl/ssl_engine.c
src/ssl/ssl_hashes.c
src/ssl/ssl_hs_client.c
src/ssl/ssl_io.c
src/ssl/ssl_rec_cbc.c
src/ssl/ssl_rec_gcm.c
src/symcipher/aes_common.c
src/symcipher/aes_small_cbcdec.c
src/symcipher/aes_small_cbcenc.c
src/symcipher/aes_small_ctr.c
src/symcipher/aes_small_dec.c
src/symcipher/aes_small_enc.c
src/x509/x509_decoder.c
'
